import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gradient-to-b from-blue-50 to-red-100">
          <div className="absolute inset-x-0 top-0 z-50 bg-transparent p-7 text-white">
            <Navbar/>
          </div>
          <div className="">
            {children}
            </div>
        </div>
      </body>
    </html>
  );
}
